#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "GameplayTagContainer.h"
#include "BPC_HitReactionSystem.generated.h"

UCLASS(Blueprintable, ClassGroup=(Framework), meta=(BlueprintSpawnableComponent))
class PG_FRAMEWORK_API UBPC_HitReactionSystem : public UActorComponent
{
	GENERATED_BODY()

public:
	UBPC_HitReactionSystem();

	UFUNCTION(BlueprintCallable, Category = "Framework|Combat")
	void PlayHitReaction(float DamageAmount, FVector HitDirection, AActor* DamageCauser);

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Framework|HitReaction")
	float FlinchThreshold = 5.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Framework|HitReaction")
	float RagdollThreshold = 50.0f;
};
