#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "BPC_ShieldDefenseSystem.generated.h"

UCLASS(Blueprintable, ClassGroup=(Framework), meta=(BlueprintSpawnableComponent))
class PG_FRAMEWORK_API UBPC_ShieldDefenseSystem : public UActorComponent
{
	GENERATED_BODY()

public:
	UBPC_ShieldDefenseSystem();

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Framework|Shield")
	float ShieldHealth = 100.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Framework|Shield")
	float MaxShieldHealth = 100.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Framework|Shield")
	float BlockAngle = 90.0f;

	UPROPERTY(BlueprintReadOnly, Category = "Framework|Shield")
	bool bShieldBroken = false;
};
